cloudconformity/documentation-api

Accounts.md
examples/node/accounts/copyRuleSetting.js

added get and patch documentation for the endpoint
v1/accounts/accountId/settings/rules/ruleId

Rule settings

---

README.md
TemplateScanner.md
examples/bash/template-scanner/scan.sh
examples/cloudformation-snippets/README.md
examples/cloudformation-snippets/S3Bucket.yml
examples/cloudformation-snippets/SNSTopic.yml
examples/cloudformation-snippets/SQSQueue.yml
examples/cloudformation-snippets/SecurityGroup.yml
examples/python/template-scanner/scan.py

1. Add Template Scanner examples in Bash and Python
2. Add CloudFormation snippets
To @sam-negotiator:
I have left a few questions to make sure I have not missed anything. I would appreciate if you take a look at my comments.

docs: PD-3886 add Template Scanner guide and link

---

Checks.md

Add documentation for suppressFail and suppressSuccess params on /checks

docs: PD-52 Add docu for new suppressed query params

---

Checks.md

Signed-off-by: Danny <danny.chan@cloudconformity.com>

docs: PD-4472 add "Resource" is a reserved word in extradata

---

TemplateScanner.md

This will update template scanner API documentation to reflect
recent integration of template scanner and profiles

docs: PD-2612 update template scanner API documentation

---

Checks.md

Signed-off-by: Danny <danny.chan@cloudconformity.com>

doc: PD-4826 update custom checks extradata description

---

Users.md

Note: Please merge https://github.com/cloudconformity/documentation-api/pull/62 first before merging this

docs: PD-5258 add new endpoint documentation for adding a sso user

---

Accounts.md

This updates the tags parameter information on the patch endpoint to include the validations for users to read

docs: PD-5799 update PATCH account end point 

---

Reports.md

- includes section list reports for either an account, group or organisation
- includes section to download a report

docs: PD-4461 GET API support for reports

---

Accounts.md

Reverts cloudconformity/documentation-api#84

Revert "feat: PD-5812-PD-6089 - add cost Package validator to account documen…"

---

Checks.md

- change to list all account checks from list all checks
- the query parameter accountIds is a required parameter to use this endpoint

docs: PD-5863 update list all checks so its more descriptive

---

Checks.md

feat: PD-4497 add uuid in example

---

Checks.md

feat: PD-4497 update Check.md doc for UUID

---

Checks.md

This reverts commit 5e200b5b28a80cc33503d379651f42ddfb9629a5.

Revert "feat: PD-4497 update Check.md doc for UUID"

---

Profiles.md

and change all "Example Request..." to "Example request..." for consistency

fix: PD-5497 fix example request wording

---

Settings.md

Reverts cloudconformity/documentation-api#126

Revert "fix: PD-6782 Change documentation to reflect changes done for PD-6782"

---

Groups.md
Users.md

- List All Groups
- Get Group Details

docs: PD-6534 Groups - view endpoints

---

.prettierrc
Accounts.md

Also
- fix typo (what are 'specifivities'?) 🤔
- remove space between 'end point'
- format JSON and tabs

fix: PD-7114 Add exceptions to example for PATCH accounts and accounts/id endpoint

---

Checks.md

Notice that this PR should be merged after [PR for PD-4497](https://github.com/cloudconformity/documentation-api/pull/113/files). It might conflict with master after PD-4497 is merged. If so, I'll rebase and push the code again.

fix PD-6522 rename uuid to providerResourceId

---

Filtering.md
ReportConfigs.md

- ReportConfigs: add example request and response for Azure accounts
- Filtering: edit wording to not be specific to AWS

impr: PD-6290 Update documentation to include references for AWS and Azure

---

ReportConfigs.md

Added "type" to example request for CREATE/UPDATE to be consistent with rest of API docs and the JSON API spec.

docs: PD-6637 Added "type" to example requests

---

Profiles.md

Also do some light Prettier-ing

feat: PD-5864 Explain the `include` field in the "Apply Profile to Accounts" section

---

open-api/resources/get/index.yml
open-api/resources/get/responses/200.yml
open-api/shared-schemas/fields/aws-regions.yml
open-api/shared-schemas/fields/azure-regions.yml

Schema updates. This resolves some of the issues raised during technical QA as listed [here](https://cloudconformity.atlassian.net/browse/PD-7404?focusedCommentId=45877).

improve: PD-7404 minor schema fixes for resources/get

---

open-api/settings/{settingId}/delete/index.yml
open-api/settings/{settingId}/get/index.yml

**Note**: Base branch is `PD-7405-settings` due to code re-use. When `PD-7405-settings` is merged into `open-api-documentation` branch, this current branch's base changed to that as well.

docs: PD-7591 Add documentation for GET and DELETE endpoints of setting/{settingId}

---

open-api/settings/{settingId}/delete/index.yml
open-api/settings/{settingId}/get/index.yml

New PR to merge onto correct branch

docs: PD-7591 Document GET and DELETE endpoints for settings/{settingId}
